export const supportedLanguages = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Ukrainian",
  "Polish",
  "Romanian",
  "Czech",
  "Hungarian",
  "Greek",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian",
  "Urdu",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Nepali",
  "Sinhala",
  "Chinese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Filipino",
  "Swahili",
  "Afrikaans",
  "Amharic",
  "Yoruba",
  "Zulu",
  "Hausa",
  "Somali",
  "Norwegian",
  "Swedish",
  "Danish",
  "Finnish",
  "Icelandic",
  "Irish",
  "Welsh",
  "Catalan",
  "Basque",
  "Galician",
  "Serbian",
  "Croatian",
  "Bosnian",
  "Bulgarian",
  "Slovak",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Albanian",
  "Georgian",
  "Armenian",
  "Azerbaijani",
] as const;

export const defaultLanguage = "English";

export function normalizeLanguage(language: unknown) {
  if (typeof language !== "string") return defaultLanguage;
  return supportedLanguages.includes(language as (typeof supportedLanguages)[number])
    ? language
    : defaultLanguage;
}
