export const supportedLanguages = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Ukrainian",
  "Polish",
  "Romanian",
  "Czech",
  "Hungarian",
  "Greek",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian",
  "Urdu",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Nepali",
  "Sinhala",
  "Chinese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Filipino",
  "Swahili",
  "Afrikaans",
  "Amharic",
  "Yoruba",
  "Zulu",
  "Hausa",
  "Somali",
  "Norwegian",
  "Swedish",
  "Danish",
  "Finnish",
  "Icelandic",
  "Irish",
  "Welsh",
  "Catalan",
  "Basque",
  "Galician",
  "Serbian",
  "Croatian",
  "Bosnian",
  "Bulgarian",
  "Slovak",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Albanian",
  "Georgian",
  "Armenian",
  "Azerbaijani",
] as const;

export const defaultLanguage = "English";
export type SupportedLanguage = (typeof supportedLanguages)[number];

const nativeLanguageNames: Record<SupportedLanguage, string> = {
  English: "English",
  Hindi: "हिन्दी",
  Spanish: "Español",
  French: "Français",
  German: "Deutsch",
  Italian: "Italiano",
  Portuguese: "Português",
  Dutch: "Nederlands",
  Russian: "Русский",
  Ukrainian: "Українська",
  Polish: "Polski",
  Romanian: "Română",
  Czech: "Čeština",
  Hungarian: "Magyar",
  Greek: "Ελληνικά",
  Turkish: "Türkçe",
  Arabic: "العربية",
  Hebrew: "עברית",
  Persian: "فارسی",
  Urdu: "اردو",
  Bengali: "বাংলা",
  Tamil: "தமிழ்",
  Telugu: "తెలుగు",
  Marathi: "मराठी",
  Gujarati: "ગુજરાતી",
  Kannada: "ಕನ್ನಡ",
  Malayalam: "മലയാളം",
  Punjabi: "ਪੰਜਾਬੀ",
  Odia: "ଓଡ଼ିଆ",
  Assamese: "অসমীয়া",
  Nepali: "नेपाली",
  Sinhala: "සිංහල",
  Chinese: "中文",
  Japanese: "日本語",
  Korean: "한국어",
  Vietnamese: "Tiếng Việt",
  Thai: "ไทย",
  Indonesian: "Bahasa Indonesia",
  Malay: "Bahasa Melayu",
  Filipino: "Filipino",
  Swahili: "Kiswahili",
  Afrikaans: "Afrikaans",
  Amharic: "አማርኛ",
  Yoruba: "Yorùbá",
  Zulu: "isiZulu",
  Hausa: "Hausa",
  Somali: "Soomaali",
  Norwegian: "Norsk",
  Swedish: "Svenska",
  Danish: "Dansk",
  Finnish: "Suomi",
  Icelandic: "Íslenska",
  Irish: "Gaeilge",
  Welsh: "Cymraeg",
  Catalan: "Català",
  Basque: "Euskara",
  Galician: "Galego",
  Serbian: "Српски",
  Croatian: "Hrvatski",
  Bosnian: "Bosanski",
  Bulgarian: "Български",
  Slovak: "Slovenčina",
  Slovenian: "Slovenščina",
  Lithuanian: "Lietuvių",
  Latvian: "Latviešu",
  Estonian: "Eesti",
  Albanian: "Shqip",
  Georgian: "ქართული",
  Armenian: "Հայերեն",
  Azerbaijani: "Azərbaycanca",
};

const languageLocaleCodes: Record<SupportedLanguage, string> = {
  English: "en-US",
  Hindi: "hi",
  Spanish: "es",
  French: "fr",
  German: "de",
  Italian: "it",
  Portuguese: "pt",
  Dutch: "nl",
  Russian: "ru",
  Ukrainian: "uk",
  Polish: "pl",
  Romanian: "ro",
  Czech: "cs",
  Hungarian: "hu",
  Greek: "el",
  Turkish: "tr",
  Arabic: "ar",
  Hebrew: "he",
  Persian: "fa",
  Urdu: "ur",
  Bengali: "bn",
  Tamil: "ta",
  Telugu: "te",
  Marathi: "mr",
  Gujarati: "gu",
  Kannada: "kn",
  Malayalam: "ml",
  Punjabi: "pa",
  Odia: "or",
  Assamese: "as",
  Nepali: "ne",
  Sinhala: "si",
  Chinese: "zh",
  Japanese: "ja",
  Korean: "ko",
  Vietnamese: "vi",
  Thai: "th",
  Indonesian: "id",
  Malay: "ms",
  Filipino: "fil",
  Swahili: "sw",
  Afrikaans: "af",
  Amharic: "am",
  Yoruba: "yo",
  Zulu: "zu",
  Hausa: "ha",
  Somali: "so",
  Norwegian: "no",
  Swedish: "sv",
  Danish: "da",
  Finnish: "fi",
  Icelandic: "is",
  Irish: "ga",
  Welsh: "cy",
  Catalan: "ca",
  Basque: "eu",
  Galician: "gl",
  Serbian: "sr",
  Croatian: "hr",
  Bosnian: "bs",
  Bulgarian: "bg",
  Slovak: "sk",
  Slovenian: "sl",
  Lithuanian: "lt",
  Latvian: "lv",
  Estonian: "et",
  Albanian: "sq",
  Georgian: "ka",
  Armenian: "hy",
  Azerbaijani: "az",
};

export const languageUrlPrefixes: Record<SupportedLanguage, string> = {
  ...languageLocaleCodes,
  English: "",
  Filipino: "fil",
} as Record<SupportedLanguage, string>;

const rtlLanguages = new Set<SupportedLanguage>(["Arabic", "Hebrew", "Persian", "Urdu"]);

export type LanguageConfig = {
  language: SupportedLanguage;
  nativeName: string;
  locale: string;
  prefix: string;
  dir: "ltr" | "rtl";
};

export const languageConfigs = Object.fromEntries(
  supportedLanguages.map((language) => [
    language,
    {
      language,
      nativeName: nativeLanguageNames[language],
      locale: languageLocaleCodes[language],
      prefix: languageUrlPrefixes[language],
      dir: rtlLanguages.has(language) ? "rtl" : "ltr",
    },
  ]),
) as Record<SupportedLanguage, LanguageConfig>;

export const languageCodeToLanguage = Object.fromEntries(
  supportedLanguages.flatMap((language) => {
    const locale = languageLocaleCodes[language].toLowerCase();
    const languageCode = locale.split("-")[0];
    return [
      [locale, language],
      [languageCode, language],
    ];
  }),
) as Record<string, SupportedLanguage>;

export const languagePrefixToLanguage = Object.fromEntries(
  supportedLanguages.flatMap((language) => {
    const prefix = languageUrlPrefixes[language];
    return prefix ? [[prefix, language]] : [];
  }),
) as Record<string, SupportedLanguage>;

export function languageDisplayName(language: SupportedLanguage | string) {
  return nativeLanguageNames[language as SupportedLanguage] ?? language;
}

export function normalizeLanguage(language: unknown): SupportedLanguage {
  if (typeof language !== "string") return defaultLanguage;
  return supportedLanguages.includes(language as SupportedLanguage)
    ? (language as SupportedLanguage)
    : defaultLanguage;
}
