export const supportedLanguages = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Ukrainian",
  "Polish",
  "Romanian",
  "Czech",
  "Hungarian",
  "Greek",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian",
  "Urdu",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Nepali",
  "Sinhala",
  "Chinese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Thai",
  "Indonesian",
  "Malay",
  "Filipino",
  "Swahili",
  "Afrikaans",
  "Amharic",
  "Yoruba",
  "Zulu",
  "Hausa",
  "Somali",
  "Norwegian",
  "Swedish",
  "Danish",
  "Finnish",
  "Icelandic",
  "Irish",
  "Welsh",
  "Catalan",
  "Basque",
  "Galician",
  "Serbian",
  "Croatian",
  "Bosnian",
  "Bulgarian",
  "Slovak",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Albanian",
  "Georgian",
  "Armenian",
  "Azerbaijani",
] as const;

export const defaultLanguage = "English";

export const nativeLanguageNames: Record<(typeof supportedLanguages)[number], string> = {
  English: "English",
  Hindi: "हिन्दी",
  Spanish: "Español",
  French: "Français",
  German: "Deutsch",
  Italian: "Italiano",
  Portuguese: "Português",
  Dutch: "Nederlands",
  Russian: "Русский",
  Ukrainian: "Українська",
  Polish: "Polski",
  Romanian: "Română",
  Czech: "Čeština",
  Hungarian: "Magyar",
  Greek: "Ελληνικά",
  Turkish: "Türkçe",
  Arabic: "العربية",
  Hebrew: "עברית",
  Persian: "فارسی",
  Urdu: "اردو",
  Bengali: "বাংলা",
  Tamil: "தமிழ்",
  Telugu: "తెలుగు",
  Marathi: "मराठी",
  Gujarati: "ગુજરાતી",
  Kannada: "ಕನ್ನಡ",
  Malayalam: "മലയാളം",
  Punjabi: "ਪੰਜਾਬੀ",
  Odia: "ଓଡ଼ିଆ",
  Assamese: "অসমীয়া",
  Nepali: "नेपाली",
  Sinhala: "සිංහල",
  Chinese: "中文",
  Japanese: "日本語",
  Korean: "한국어",
  Vietnamese: "Tiếng Việt",
  Thai: "ไทย",
  Indonesian: "Bahasa Indonesia",
  Malay: "Bahasa Melayu",
  Filipino: "Filipino",
  Swahili: "Kiswahili",
  Afrikaans: "Afrikaans",
  Amharic: "አማርኛ",
  Yoruba: "Yorùbá",
  Zulu: "isiZulu",
  Hausa: "Hausa",
  Somali: "Soomaali",
  Norwegian: "Norsk",
  Swedish: "Svenska",
  Danish: "Dansk",
  Finnish: "Suomi",
  Icelandic: "Íslenska",
  Irish: "Gaeilge",
  Welsh: "Cymraeg",
  Catalan: "Català",
  Basque: "Euskara",
  Galician: "Galego",
  Serbian: "Српски",
  Croatian: "Hrvatski",
  Bosnian: "Bosanski",
  Bulgarian: "Български",
  Slovak: "Slovenčina",
  Slovenian: "Slovenščina",
  Lithuanian: "Lietuvių",
  Latvian: "Latviešu",
  Estonian: "Eesti",
  Albanian: "Shqip",
  Georgian: "ქართული",
  Armenian: "Հայերեն",
  Azerbaijani: "Azərbaycanca",
};

export function languageDisplayName(language: (typeof supportedLanguages)[number] | string) {
  return nativeLanguageNames[language as (typeof supportedLanguages)[number]] ?? language;
}

export function normalizeLanguage(language: unknown) {
  if (typeof language !== "string") return defaultLanguage;
  return supportedLanguages.includes(language as (typeof supportedLanguages)[number])
    ? language
    : defaultLanguage;
}
