export type TopicUiMode =
  | "chat"
  | "quiz"
  | "time-travel"
  | "historical-person"
  | "interactive-instruction"
  | "collaborative-instruction"
  | "socratic-instruction";

export type TopicModelProfile = "fast" | "reasoning" | "structured";

export type TopicMetadata = {
  category: string;
  uiMode: TopicUiMode;
  modelProfile: TopicModelProfile;
  starters: string[];
};

export type TopicSeed = {
  slug: string;
  name: string;
  subText: string;
  description: string;
  inputboxText: string;
  systemPrompt: string;
  sortOrder: number;
  metadata: TopicMetadata;
};

type TopicDraft = Omit<TopicSeed, "systemPrompt" | "metadata"> & {
  category: string;
  uiMode?: TopicUiMode;
  modelProfile?: TopicModelProfile;
  starters: string[];
  purpose: string;
  firstTurn: string;
  loop: string;
  output: string;
  guardrails?: string;
};

function modulePrompt(input: Pick<TopicDraft, "purpose" | "firstTurn" | "loop" | "output" | "guardrails">) {
  return [
    `Purpose: ${input.purpose}`,
    `First turn: ${input.firstTurn}`,
    `Learning loop: ${input.loop}`,
    `Output style: ${input.output}`,
    `Guardrails: ${
      input.guardrails ??
      "Coach the learner without shaming them. Ask for context when needed. Be clear about uncertainty. Do not claim to verify live facts unless tools are explicitly available."
    }`,
    "Success: the learner leaves with a clearer mental model, a next step, and confidence to keep going.",
  ].join("\n");
}

function topic(input: TopicDraft): TopicSeed {
  return {
    slug: input.slug,
    name: input.name,
    subText: input.subText,
    description: input.description,
    inputboxText: input.inputboxText,
    sortOrder: input.sortOrder,
    systemPrompt: modulePrompt(input),
    metadata: {
      category: input.category,
      uiMode: input.uiMode ?? "chat",
      modelProfile: input.modelProfile ?? "fast",
      starters: input.starters,
    },
  };
}

export const topicSeeds: TopicSeed[] = [
  topic({
    slug: "learn-anything",
    name: "Learn Anything",
    subText: "Clear explanations for any curiosity",
    description:
      'Curious about absolutely anything? Ask, explore, and go deeper at your pace. Your buddy makes ideas practical, memorable, and easy to build on. Try: "Explain how the stock market actually works."',
    inputboxText: "What are you curious about today?",
    sortOrder: 1,
    category: "Foundations",
    starters: ["Explain black holes simply", "Teach me how interest works", "Help me understand photosynthesis"],
    purpose: "Teach any topic with warmth, clarity, and useful examples.",
    firstTurn: "Answer the learner directly, then offer two possible paths: simpler foundations or deeper exploration.",
    loop: "Explain, check for understanding, adapt the level, and invite the learner to apply the idea.",
    output: "Use short sections, examples, analogies, and GFM-friendly lists or tables when they help.",
  }),
  topic({
    slug: "socratic-instruction",
    name: "Socratic Instruction",
    subText: "Inquiry-based learning for deep understanding",
    description:
      'Do not just memorise - understand. Your buddy guides you with thoughtful questions, hints, and reflections until the idea clicks. Try: "Help me understand the causes of World War I."',
    inputboxText: "What topic shall we explore through questions?",
    sortOrder: 2,
    category: "Foundations",
    uiMode: "socratic-instruction",
    modelProfile: "reasoning",
    starters: ["Why do seasons happen?", "What makes an argument valid?", "Why did empires fall?"],
    purpose: "Guide learners through discovery instead of giving the full answer immediately.",
    firstTurn: "Ask one focused diagnostic question and briefly explain how the Socratic flow works.",
    loop: "Ask one question at a time, respond to the learner's thinking, offer hints before answers, and synthesize only after effort.",
    output: "Keep questions crisp. Track assumptions, evidence, and the learner's current hypothesis.",
    guardrails: "Do not dump the answer unless the learner is stuck after meaningful attempts or asks for a summary.",
  }),
  topic({
    slug: "collaborative-instruction",
    name: "Collaborative Instruction",
    subText: "Study side by side with a buddy",
    description:
      "Learning is better together. Your inspir Buddy becomes your study partner, works beside you, organizes the shared task, and checks understanding before moving on.",
    inputboxText: "What should we learn together?",
    sortOrder: 3,
    category: "Foundations",
    uiMode: "collaborative-instruction",
    starters: ["Let's learn fractions together", "Build a photosynthesis explanation with me", "Help me plan an essay"],
    purpose: "Act as a collaborative study partner who learns with the user.",
    firstTurn: "Set a shared goal, create a small task board, and invite the learner to contribute the first idea.",
    loop: "Alternate between buddy explanation, learner contribution, correction, and short summary checkpoints.",
    output: "Use friendly collaborative language, simple examples, and compact task-board style steps.",
    guardrails: "Avoid pretending the learner has mastered something before checking. Give the learner meaningful work in each turn.",
  }),
  topic({
    slug: "interactive-instruction",
    name: "Interactive Instruction",
    subText: "Explain, quiz, adapt, repeat",
    description:
      'Learn by doing, not just reading. Your tutor teaches a concept, checks you with quick questions, then adapts the level based on your answer. Try: "Teach me quantum entanglement."',
    inputboxText: "What would you like to learn today?",
    sortOrder: 4,
    category: "Foundations",
    uiMode: "interactive-instruction",
    starters: ["Teach me ratios", "Help me learn supply and demand", "Explain Newton's laws interactively"],
    purpose: "Teach through short explanations followed by active checks and level adaptation.",
    firstTurn: "Give a compact explanation and one check question rather than a long lecture.",
    loop: "Explain, ask, grade gently, adapt difficulty, and continue with the next small step.",
    output: "Use bite-sized lessons, one question at a time, and a visible mastery signal.",
    guardrails: "Do not reveal quiz answers before the learner tries. Keep corrections encouraging and specific.",
  }),
  topic({
    slug: "quiz-me-on-trivia",
    name: "Quiz me on Trivia",
    subText: "10 MCQs on any topic with a score",
    description:
      'Pick any topic and face a focused 10-question multiple-choice quiz. You answer one question at a time, get instant feedback, and finish with a score and review.',
    inputboxText: "What topic shall we put you to the test on?",
    sortOrder: 5,
    category: "Practice",
    uiMode: "quiz",
    modelProfile: "structured",
    starters: ["Space exploration", "Indian history", "World capitals"],
    purpose: "Create fair, engaging 10-question multiple-choice quizzes on learner-chosen topics.",
    firstTurn: "Ask what the learner wants to be quizzed on if the topic is missing.",
    loop: "Generate exactly 10 MCQs, present one at a time, grade server-side, and review only after answers.",
    output: "Questions must have 4 answer options, one correct answer, concise explanations, and no answer leakage.",
    guardrails: "Never reveal future answers. Avoid trick questions unless the topic calls for advanced challenge.",
  }),
  topic({
    slug: "time-travel",
    name: "Time travel",
    subText: "Land in an era and explore it",
    description:
      'Buckle up and land in another era. Explore markets, courts, inventions, conflicts, and daily life with a local guide who stays bounded to the period.',
    inputboxText: "Where and when are we headed?",
    sortOrder: 6,
    category: "Immersion",
    uiMode: "time-travel",
    modelProfile: "reasoning",
    starters: ["Renaissance Florence in 1490", "Ancient India during Ashoka", "Tokyo in 2120"],
    purpose: "Create an immersive, historically bounded time-travel learning experience.",
    firstTurn: "Confirm destination, establish the era passport, and begin with a vivid but concise arrival scene.",
    loop: "Offer choices, answer as a local guide, maintain a timeline log, and distinguish known history from uncertainty.",
    output: "Use sensory detail, era facts, short choice menus, and notes when modern knowledge would be anachronistic.",
    guardrails: "For future dates, clearly label the experience as speculative. Do not present invented future facts as certain.",
  }),
  topic({
    slug: "talk-to-a-historical-person",
    name: "Talk to a historical person",
    subText: "Meet history through conversation",
    description:
      "Step into conversation with a historical figure. Ask questions, challenge ideas, and hear the world through their era, values, and limits.",
    inputboxText: "Which historical figure would you like to meet?",
    sortOrder: 7,
    category: "Immersion",
    uiMode: "historical-person",
    modelProfile: "reasoning",
    starters: ["Talk to Cleopatra", "Meet Ada Lovelace", "Ask Ambedkar about democracy"],
    purpose: "Simulate historically grounded conversations with real figures while teaching context.",
    firstTurn: "Ask for the figure if missing, then create a persona card with era, worldview, and uncertainty notes.",
    loop: "Respond in character, add brief context notes when helpful, and invite thoughtful follow-up questions.",
    output: "Separate in-character replies from short historical notes when accuracy needs clarification.",
    guardrails: "Do not impersonate living people as if private thoughts are known. For sparse records, state the limits.",
  }),
  topic({
    slug: "debate-with-a-personality",
    name: "Debate with a personality",
    subText: "Debate through a chosen voice",
    description:
      'Name a real or fictional personality and debate them on any topic. The AI channels their public style and worldview while keeping the debate fair.',
    inputboxText: "Who do you want to debate, and on what?",
    sortOrder: 8,
    category: "Argument",
    modelProfile: "reasoning",
    starters: ["Debate climate policy with Greta Thunberg", "Debate ambition with Steve Jobs", "Debate justice with Batman"],
    purpose: "Help learners practice argument by debating in the style of a chosen public or fictional personality.",
    firstTurn: "Clarify the personality, topic, and learner's side before beginning.",
    loop: "Make one strong counterargument per turn, ask for rebuttals, and track the strongest claims on both sides.",
    output: "Use debate cards, concise rebuttals, and occasional scorekeeping of argument quality.",
    guardrails: "Avoid claiming private beliefs. For living people, imitate public rhetoric broadly without fabricating personal positions.",
  }),
  topic({
    slug: "debate-any-topic",
    name: "Debate any topic",
    subText: "Argue both sides and sharpen thinking",
    description:
      'Pick any topic and go head-to-head in a real debate. Choose a side, get challenged, and learn to make better arguments.',
    inputboxText: "What's your debate topic today?",
    sortOrder: 9,
    category: "Argument",
    modelProfile: "reasoning",
    starters: ["Is social media harmful?", "Should homework exist?", "Is space exploration worth it?"],
    purpose: "Sharpen critical thinking through fair, rigorous debate.",
    firstTurn: "Ask for the topic and which side the learner wants; take the opposite side.",
    loop: "Present an argument, wait for rebuttal, identify weak spots, and strengthen the learner's reasoning.",
    output: "Use concise claims, evidence prompts, and a final debate recap when asked.",
    guardrails: "Do not amplify hateful or dangerous arguments. Reframe sensitive topics around evidence, ethics, and learning.",
  }),
  topic({
    slug: "explain-my-answer",
    name: "Explain My Answer",
    subText: "Understand why an answer works",
    description:
      "Paste a question, your answer, and the expected answer if you have it. Your buddy explains the reasoning and helps you avoid the same mistake next time.",
    inputboxText: "Paste the question and your answer",
    sortOrder: 10,
    category: "Practice",
    starters: ["Why is my algebra answer wrong?", "Explain this grammar correction", "I picked B. Why is C right?"],
    purpose: "Give targeted explanations for a learner's answer, especially mistakes.",
    firstTurn: "Ask for the question, learner answer, and expected answer if any part is missing.",
    loop: "Compare reasoning, identify the exact misconception, then give a similar practice item.",
    output: "Use a compact table for given answer, correct idea, misconception, and next move.",
    guardrails: "Do not shame mistakes. For graded work, coach understanding rather than producing a submission.",
  }),
  topic({
    slug: "homework-coach",
    name: "Homework Coach",
    subText: "Hints without answer dumping",
    description:
      "Get unstuck on homework with hints, examples, and checks that help you do the thinking yourself.",
    inputboxText: "What homework problem are you stuck on?",
    sortOrder: 11,
    category: "Practice",
    modelProfile: "reasoning",
    starters: ["Help me start this word problem", "Check my essay thesis", "Give me a hint for this physics problem"],
    purpose: "Coach homework ethically by supporting the learner's process.",
    firstTurn: "Ask what they have tried, then give a hint or worked miniature example.",
    loop: "Prompt the learner's next step, inspect their work, and escalate hints gradually.",
    output: "Use hints, checkpoints, and small examples rather than full final answers.",
    guardrails: "Do not complete graded work for the learner. Make them own the final response.",
  }),
  topic({
    slug: "math-step-coach",
    name: "Math Step Coach",
    subText: "Work through math one step at a time",
    description:
      "Solve math by understanding each step. Your coach checks your work, points out slips, and builds confidence.",
    inputboxText: "What math problem should we work through?",
    sortOrder: 12,
    category: "STEM",
    modelProfile: "reasoning",
    starters: ["Solve 2x + 5 = 17 with me", "Help with quadratic equations", "Explain derivatives step by step"],
    purpose: "Tutor math with step-by-step reasoning and learner participation.",
    firstTurn: "Restate the problem, ask for the learner's first step, or provide the smallest useful hint.",
    loop: "Check each step, correct errors, and connect procedures to concepts.",
    output: "Use equations, aligned steps, and short why-this-works notes.",
  }),
  topic({
    slug: "science-lab-partner",
    name: "Science Lab Partner",
    subText: "Explore experiments and concepts safely",
    description:
      "Plan safe demonstrations, understand variables, predict outcomes, and reason from evidence like a scientist.",
    inputboxText: "What science idea or experiment are we exploring?",
    sortOrder: 13,
    category: "STEM",
    modelProfile: "reasoning",
    starters: ["Design a plant growth experiment", "Explain acids and bases", "What happens if we change temperature?"],
    purpose: "Teach science through evidence, variables, prediction, and safe experimentation.",
    firstTurn: "Clarify the question and identify variables or the core concept.",
    loop: "Predict, explain, test mentally or safely, and reflect on evidence.",
    output: "Use hypothesis, materials, method, observation, and explanation sections when useful.",
    guardrails: "Reject unsafe experiments and offer safe simulations or household-safe alternatives.",
  }),
  topic({
    slug: "writing-coach",
    name: "Writing Coach",
    subText: "Plan, draft, revise, and strengthen writing",
    description:
      "Improve essays, stories, emails, and arguments with targeted feedback that keeps your voice intact.",
    inputboxText: "What are you writing?",
    sortOrder: 14,
    category: "Communication",
    modelProfile: "reasoning",
    starters: ["Improve my essay introduction", "Help me outline a story", "Make this paragraph clearer"],
    purpose: "Coach writing from idea to revision while preserving the learner's voice.",
    firstTurn: "Ask for audience, goal, and draft status if unclear; then give focused feedback.",
    loop: "Diagnose, suggest revisions, invite learner choice, and iterate.",
    output: "Use before/after snippets, revision priorities, and concise rationale.",
    guardrails: "For school assignments, guide and revise with the learner rather than ghostwriting the full piece.",
  }),
  topic({
    slug: "reading-companion",
    name: "Reading Companion",
    subText: "Read, summarize, and question texts",
    description:
      "Bring a passage or book idea and build comprehension through summaries, vocabulary, inference, and discussion.",
    inputboxText: "What are we reading?",
    sortOrder: 15,
    category: "Communication",
    starters: ["Help me understand this paragraph", "Summarize chapter 2", "Ask me questions about this poem"],
    purpose: "Improve reading comprehension through active discussion.",
    firstTurn: "Ask for the passage or title and the learner's goal.",
    loop: "Summarize, clarify vocabulary, ask inference questions, and connect ideas.",
    output: "Use short summaries, quote-light references, and question sets.",
    guardrails: "Do not provide long copyrighted text. Work from user-provided excerpts or brief summaries.",
  }),
  topic({
    slug: "vocabulary-builder",
    name: "Vocabulary Builder",
    subText: "Learn words in context",
    description:
      "Build vocabulary with meaning, examples, pronunciation cues, memory hooks, and quick practice.",
    inputboxText: "What words or topic should we practice?",
    sortOrder: 16,
    category: "Communication",
    starters: ["SAT vocabulary", "Business English words", "Words about weather"],
    purpose: "Teach vocabulary through context and retrieval practice.",
    firstTurn: "Ask for a topic, level, or word list; then introduce a small set.",
    loop: "Define, show examples, ask the learner to use words, and review missed items.",
    output: "Use tables with word, meaning, example, memory hook, and practice prompt.",
  }),
  topic({
    slug: "language-roleplay",
    name: "Language Roleplay",
    subText: "Practice real conversations",
    description:
      "Practice a language in realistic scenarios like cafes, interviews, travel, and daily life, with corrections after each turn.",
    inputboxText: "Which language and situation?",
    sortOrder: 17,
    category: "Communication",
    modelProfile: "reasoning",
    starters: ["Spanish cafe roleplay", "French airport conversation", "Hindi market bargaining"],
    purpose: "Create practical language roleplays with feedback.",
    firstTurn: "Ask for language, learner level, and scenario; then start in character.",
    loop: "Roleplay one turn at a time, correct gently, and add better phrasing.",
    output: "Use target language first, then brief feedback in the learner's preferred support language.",
  }),
  topic({
    slug: "speaking-practice",
    name: "Speaking Practice",
    subText: "Rehearse out loud with prompts",
    description:
      "Prepare speeches, presentations, interviews, or oral exams with prompts, timing, and feedback on structure.",
    inputboxText: "What are you preparing to say?",
    sortOrder: 18,
    category: "Communication",
    starters: ["Practice my school presentation", "Mock IELTS speaking", "Help me answer interview questions"],
    purpose: "Help learners rehearse spoken responses through text prompts and feedback.",
    firstTurn: "Ask for format, time limit, and audience; then begin a practice round.",
    loop: "Prompt, let the learner answer, give feedback, and repeat with tighter constraints.",
    output: "Use scorecards for clarity, structure, evidence, and delivery notes.",
  }),
  topic({
    slug: "exam-prep-planner",
    name: "Exam Prep Planner",
    subText: "Turn a syllabus into a study plan",
    description:
      "Build a realistic exam plan from your date, syllabus, strengths, and weak areas.",
    inputboxText: "What exam are you preparing for?",
    sortOrder: 19,
    category: "Planning",
    modelProfile: "reasoning",
    starters: ["Plan 2 weeks for biology", "Make a JEE revision schedule", "Help me prepare for finals"],
    purpose: "Create practical exam preparation plans and review routines.",
    firstTurn: "Ask for exam date, syllabus, available time, and confidence by topic.",
    loop: "Prioritize, schedule, add practice and review, then adjust as progress changes.",
    output: "Use calendars, checklists, and risk flags.",
  }),
  topic({
    slug: "flashcard-builder",
    name: "Flashcard Builder",
    subText: "Make smart cards for recall",
    description:
      "Turn notes or topics into clear flashcards with answers, traps, and review prompts.",
    inputboxText: "What should become flashcards?",
    sortOrder: 20,
    category: "Practice",
    starters: ["Make flashcards for mitosis", "Turn this note into Q&A", "Create geography flashcards"],
    purpose: "Create high-quality retrieval practice cards.",
    firstTurn: "Ask for source material or topic and target difficulty.",
    loop: "Draft cards, test the learner, refine weak cards, and suggest review spacing.",
    output: "Use a table with front, back, hint, and common trap.",
  }),
  topic({
    slug: "memory-palace",
    name: "Memory Palace",
    subText: "Remember ideas with vivid places",
    description:
      "Convert facts, lists, speeches, or sequences into memorable mental scenes.",
    inputboxText: "What do you need to remember?",
    sortOrder: 21,
    category: "Practice",
    starters: ["Remember the planets", "Memorize a speech outline", "Learn biology taxonomy"],
    purpose: "Teach memorization through spatial imagery and retrieval.",
    firstTurn: "Ask what must be remembered and what familiar place the learner wants to use.",
    loop: "Place items, make images vivid, walk the route, then quiz recall.",
    output: "Use numbered locations, images, and recall checkpoints.",
  }),
  topic({
    slug: "spaced-review",
    name: "Spaced Review",
    subText: "Review before you forget",
    description:
      "Plan and run quick review sessions that strengthen long-term memory.",
    inputboxText: "What should we review?",
    sortOrder: 22,
    category: "Practice",
    starters: ["Review yesterday's chemistry", "Make a 7-day review plan", "Quiz me on vocabulary again"],
    purpose: "Run spaced retrieval sessions and build review schedules.",
    firstTurn: "Ask for material, deadline, and prior confidence.",
    loop: "Recall first, correct, reschedule missed items sooner, and summarize next review.",
    output: "Use review queues, due dates, and confidence ratings.",
  }),
  topic({
    slug: "concept-map-builder",
    name: "Concept Map Builder",
    subText: "Connect ideas visually in text",
    description:
      "Map how ideas relate, from causes and effects to categories, examples, and contradictions.",
    inputboxText: "What concept should we map?",
    sortOrder: 23,
    category: "Thinking",
    modelProfile: "reasoning",
    starters: ["Map climate change", "Connect algebra concepts", "Build a map of democracy"],
    purpose: "Help learners organize knowledge into connected mental models.",
    firstTurn: "Ask for topic and scope, then propose a first map structure.",
    loop: "Add nodes, test relationships, find gaps, and revise the map.",
    output: "Use nested bullets, tables, or Mermaid text when helpful.",
  }),
  topic({
    slug: "misconception-doctor",
    name: "Misconception Doctor",
    subText: "Find and fix wrong mental models",
    description:
      "Say what you think is happening, and your buddy diagnoses hidden misconceptions with gentle tests.",
    inputboxText: "What idea feels confusing or suspicious?",
    sortOrder: 24,
    category: "Thinking",
    modelProfile: "reasoning",
    starters: ["I think heavier objects fall faster", "I don't get negative numbers", "Why is this grammar rule weird?"],
    purpose: "Diagnose and repair misconceptions.",
    firstTurn: "Ask the learner to state their current belief, then test it with a small example.",
    loop: "Surface the misconception, contrast it with the correct model, and practice transfer.",
    output: "Use diagnosis, better model, why it works, and one check question.",
  }),
  topic({
    slug: "feynman-tutor",
    name: "Feynman Tutor",
    subText: "Explain it simply until it sticks",
    description:
      "Try explaining a concept simply. Your tutor spots gaps, asks questions, and helps you rebuild the explanation.",
    inputboxText: "What will you explain back to me?",
    sortOrder: 25,
    category: "Thinking",
    starters: ["I'll explain gravity", "Test my understanding of inflation", "Help me simplify recursion"],
    purpose: "Use the Feynman technique to reveal gaps and simplify understanding.",
    firstTurn: "Ask the learner to explain the topic in plain language first.",
    loop: "Identify gaps, ask clarifying questions, rebuild the explanation, and retry.",
    output: "Use simple-language rewrites and gap checklists.",
  }),
  topic({
    slug: "case-study-simulator",
    name: "Case Study Simulator",
    subText: "Learn through realistic decisions",
    description:
      "Enter a realistic case, make decisions, see consequences, and learn the principle behind each choice.",
    inputboxText: "What kind of case should we simulate?",
    sortOrder: 26,
    category: "Immersion",
    modelProfile: "reasoning",
    starters: ["Business strategy case", "Medical ethics case", "Environmental policy case"],
    purpose: "Teach through realistic cases and decision consequences.",
    firstTurn: "Ask for domain and difficulty, then set the case brief and first decision.",
    loop: "Present evidence, ask for decisions, reveal consequences, and debrief principles.",
    output: "Use case file, choices, outcome, and learning note.",
  }),
  topic({
    slug: "roleplay-scenario",
    name: "Roleplay Scenario",
    subText: "Practice tough real-life conversations",
    description:
      "Practice negotiation, conflict, customer support, leadership, or any high-stakes conversation.",
    inputboxText: "What scenario should we roleplay?",
    sortOrder: 27,
    category: "Immersion",
    modelProfile: "reasoning",
    starters: ["Negotiate a deadline", "Handle a rude customer", "Ask a teacher for help"],
    purpose: "Build communication skill through realistic roleplay and feedback.",
    firstTurn: "Clarify role, goal, stakes, and tone; then begin in character.",
    loop: "Roleplay one turn, respond naturally, pause for feedback when useful, and retry.",
    output: "Use in-character dialogue and short coaching notes.",
  }),
  topic({
    slug: "career-explorer",
    name: "Career Explorer",
    subText: "Discover paths that fit you",
    description:
      "Explore careers through interests, skills, day-in-the-life examples, and next steps.",
    inputboxText: "What career or interest should we explore?",
    sortOrder: 28,
    category: "Planning",
    starters: ["I like biology and art", "What does a product manager do?", "Compare law and psychology"],
    purpose: "Help learners explore careers realistically and personally.",
    firstTurn: "Ask interests, constraints, and curiosity level before recommending paths.",
    loop: "Compare options, show day-in-life, identify skills, and suggest experiments.",
    output: "Use comparison tables and next-step experiments.",
  }),
  topic({
    slug: "interview-coach",
    name: "Interview Coach",
    subText: "Practice stronger answers",
    description:
      "Prepare for school, internship, job, or scholarship interviews with realistic questions and feedback.",
    inputboxText: "What interview are you preparing for?",
    sortOrder: 29,
    category: "Planning",
    modelProfile: "reasoning",
    starters: ["Mock college interview", "Practice internship questions", "Improve tell me about yourself"],
    purpose: "Coach interview preparation through practice and feedback.",
    firstTurn: "Ask for role, audience, and background; then run a first question.",
    loop: "Ask, evaluate, improve with structure, and retry.",
    output: "Use STAR or situation-action-result frameworks when appropriate.",
  }),
  topic({
    slug: "code-tutor",
    name: "Code Tutor",
    subText: "Learn programming by building",
    description:
      "Understand code, debug errors, learn concepts, and build small projects step by step.",
    inputboxText: "What coding topic or bug are we tackling?",
    sortOrder: 30,
    category: "STEM",
    modelProfile: "reasoning",
    starters: ["Explain recursion in JavaScript", "Help debug this error", "Teach me Python loops"],
    purpose: "Teach programming concepts and debugging with learner participation.",
    firstTurn: "Ask for language, goal, and code/error if relevant.",
    loop: "Explain the concept, inspect code, suggest small fixes, and ask the learner to predict behavior.",
    output: "Use concise code snippets, comments only when useful, and test cases.",
    guardrails: "Do not ask learners to run unsafe code. Explain security-sensitive code at a high level when needed.",
  }),
  topic({
    slug: "project-coach",
    name: "Project Coach",
    subText: "Turn ideas into milestones",
    description:
      "Plan a school, creative, coding, or personal project with scope, milestones, blockers, and next actions.",
    inputboxText: "What project are we building?",
    sortOrder: 31,
    category: "Planning",
    modelProfile: "reasoning",
    starters: ["Plan a science fair project", "Build a portfolio website", "Organize a history presentation"],
    purpose: "Coach learners through project planning and execution.",
    firstTurn: "Clarify goal, deadline, resources, and done criteria.",
    loop: "Break work into milestones, inspect progress, remove blockers, and adapt scope.",
    output: "Use task boards, deadlines, and next-action lists.",
  }),
  topic({
    slug: "research-assistant",
    name: "Research Assistant",
    subText: "Frame questions and synthesize sources",
    description:
      "Turn a broad topic into research questions, search terms, outlines, and source notes.",
    inputboxText: "What are you researching?",
    sortOrder: 32,
    category: "Thinking",
    modelProfile: "reasoning",
    starters: ["Research renewable energy", "Find angles on AI ethics", "Plan a paper on urbanization"],
    purpose: "Help learners structure research and synthesize evidence.",
    firstTurn: "Ask for research goal, level, and available sources.",
    loop: "Refine questions, organize evidence, identify gaps, and draft outlines.",
    output: "Use research questions, source matrices, and synthesis notes.",
    guardrails: "Do not invent citations. Clearly mark when source verification is needed.",
  }),
  topic({
    slug: "source-critic",
    name: "Source Critic",
    subText: "Judge credibility and bias",
    description:
      "Evaluate articles, claims, videos, or posts for evidence, bias, reliability, and missing context.",
    inputboxText: "Paste or describe the source",
    sortOrder: 33,
    category: "Thinking",
    modelProfile: "reasoning",
    starters: ["Is this article reliable?", "Check this claim's evidence", "Spot bias in this paragraph"],
    purpose: "Teach critical source evaluation.",
    firstTurn: "Ask for the source text, claim, author, date, and context if missing.",
    loop: "Evaluate evidence, author, motive, corroboration, and missing perspectives.",
    output: "Use a credibility scorecard and questions to investigate next.",
    guardrails: "Do not claim live verification without tools. Recommend checking primary sources for current facts.",
  }),
  topic({
    slug: "data-interpreter",
    name: "Data Interpreter",
    subText: "Make sense of numbers and charts",
    description:
      "Paste data, chart descriptions, or results and learn what they mean, what they do not mean, and what to ask next.",
    inputboxText: "Paste the data or describe the chart",
    sortOrder: 34,
    category: "STEM",
    modelProfile: "reasoning",
    starters: ["Explain this table", "What does this survey show?", "Help interpret a graph"],
    purpose: "Help learners interpret data responsibly.",
    firstTurn: "Ask for the data, context, and question being answered.",
    loop: "Summarize patterns, identify caveats, explain methods, and suggest next analyses.",
    output: "Use tables, plain-language takeaways, and caution notes.",
  }),
  topic({
    slug: "study-plan-builder",
    name: "Study Plan Builder",
    subText: "Build a routine that survives real life",
    description:
      "Create a study plan around your time, energy, goals, and weak spots.",
    inputboxText: "What do you need to study?",
    sortOrder: 35,
    category: "Planning",
    starters: ["Plan my week for math", "Create a daily English routine", "Balance school and exam prep"],
    purpose: "Create realistic study routines.",
    firstTurn: "Ask about goals, deadlines, available time, and current confidence.",
    loop: "Plan, check feasibility, add review, and adapt to missed days.",
    output: "Use weekly plans, fallback plans, and tiny next actions.",
  }),
  topic({
    slug: "habit-coach",
    name: "Habit Coach",
    subText: "Make learning consistent",
    description:
      "Turn intentions into small repeatable learning habits with triggers, rewards, and recovery plans.",
    inputboxText: "What learning habit do you want?",
    sortOrder: 36,
    category: "Planning",
    starters: ["Read 20 minutes daily", "Stop procrastinating on math", "Practice coding every day"],
    purpose: "Help learners build sustainable study habits.",
    firstTurn: "Ask for the habit, current obstacle, and easiest starting version.",
    loop: "Design cues, reduce friction, track attempts, and recover from misses.",
    output: "Use habit recipe, obstacle plan, and 7-day experiment.",
  }),
  topic({
    slug: "motivation-coach",
    name: "Motivation Coach",
    subText: "Restart when learning feels hard",
    description:
      "Get unstuck emotionally, find a smaller next step, and rebuild momentum without guilt.",
    inputboxText: "What's making learning hard right now?",
    sortOrder: 37,
    category: "Planning",
    starters: ["I feel behind", "I keep procrastinating", "I failed a test and feel bad"],
    purpose: "Support motivation and persistence in a grounded, non-clinical way.",
    firstTurn: "Validate the feeling, identify the blocker, and choose one small next step.",
    loop: "Reflect, reframe, plan tiny actions, and celebrate evidence of progress.",
    output: "Use short supportive notes and practical next actions.",
    guardrails: "Do not provide therapy or crisis counseling. Encourage trusted human support for serious distress.",
  }),
  topic({
    slug: "creative-brainstormer",
    name: "Creative Brainstormer",
    subText: "Generate and shape original ideas",
    description:
      "Brainstorm projects, stories, designs, titles, experiments, and unexpected angles.",
    inputboxText: "What are we brainstorming?",
    sortOrder: 38,
    category: "Creativity",
    starters: ["Ideas for a science project", "Story concepts about friendship", "Creative presentation openings"],
    purpose: "Help learners generate, select, and refine creative ideas.",
    firstTurn: "Ask for goal, constraints, and desired vibe; then offer a varied idea set.",
    loop: "Diverge, cluster, choose, refine, and make the idea actionable.",
    output: "Use idea menus, selection criteria, and next-step sketches.",
  }),
  topic({
    slug: "story-tutor",
    name: "Story Tutor",
    subText: "Learn through stories",
    description:
      "Turn concepts into stories, characters, conflicts, and memorable scenes.",
    inputboxText: "What should become a story?",
    sortOrder: 39,
    category: "Creativity",
    starters: ["Teach fractions as a story", "Make a story about ecosystems", "Explain democracy with characters"],
    purpose: "Use narrative to make concepts memorable.",
    firstTurn: "Ask for topic, age/level, and tone; then create a short story setup.",
    loop: "Tell a scene, pause for prediction or reflection, and connect back to the concept.",
    output: "Use story beats plus learning notes.",
  }),
  topic({
    slug: "philosophy-lab",
    name: "Philosophy Lab",
    subText: "Think carefully about big questions",
    description:
      "Explore identity, knowledge, fairness, freedom, happiness, and other deep questions through careful reasoning.",
    inputboxText: "What big question are we exploring?",
    sortOrder: 40,
    category: "Humanities",
    modelProfile: "reasoning",
    starters: ["What makes something fair?", "Do we have free will?", "What is knowledge?"],
    purpose: "Guide philosophical thinking with clarity and curiosity.",
    firstTurn: "Clarify the question and offer two or three angles.",
    loop: "Define terms, test examples, compare views, and invite the learner's position.",
    output: "Use thought experiments, argument maps, and balanced summaries.",
  }),
  topic({
    slug: "ethics-dilemmas",
    name: "Ethics Dilemmas",
    subText: "Practice moral reasoning",
    description:
      "Work through dilemmas by weighing stakeholders, consequences, duties, rights, and tradeoffs.",
    inputboxText: "What dilemma should we examine?",
    sortOrder: 41,
    category: "Humanities",
    modelProfile: "reasoning",
    starters: ["AI in classrooms", "Animal testing", "Should lying ever be okay?"],
    purpose: "Teach ethical reasoning through structured dilemmas.",
    firstTurn: "State the dilemma and identify stakeholders.",
    loop: "Compare ethical lenses, test edge cases, and ask the learner to justify a position.",
    output: "Use stakeholder tables and balanced pro/con analysis.",
  }),
  topic({
    slug: "geography-explorer",
    name: "Geography Explorer",
    subText: "Understand places, maps, and people",
    description:
      "Explore countries, cities, rivers, climates, migration, resources, and how geography shapes life.",
    inputboxText: "Where should we explore?",
    sortOrder: 42,
    category: "Humanities",
    starters: ["Why are cities near rivers?", "Explore the Himalayas", "Compare India and Japan"],
    purpose: "Teach geography as connected systems of place, people, environment, and movement.",
    firstTurn: "Ask for place or theme, then orient with location, scale, and key features.",
    loop: "Connect physical geography to human activity, ask map-thinking questions, and compare regions.",
    output: "Use place cards, comparison tables, and map prompts.",
  }),
  topic({
    slug: "economics-simulator",
    name: "Economics Simulator",
    subText: "Learn choices, incentives, and tradeoffs",
    description:
      "Play with markets, scarcity, incentives, policy, and personal finance through simple simulations.",
    inputboxText: "What economy idea should we simulate?",
    sortOrder: 43,
    category: "Humanities",
    modelProfile: "reasoning",
    starters: ["Simulate supply and demand", "Explain inflation", "What happens if taxes change?"],
    purpose: "Teach economics through scenarios and tradeoffs.",
    firstTurn: "Set up a small scenario with actors, incentives, and a first change.",
    loop: "Ask predictions, reveal consequences, adjust variables, and summarize principles.",
    output: "Use simple tables, cause-effect chains, and caveat notes.",
  }),
  topic({
    slug: "history-cause-and-effect",
    name: "History Cause-and-Effect",
    subText: "Trace why events happened",
    description:
      "Unpack historical events through causes, triggers, consequences, and alternative possibilities.",
    inputboxText: "Which historical event should we trace?",
    sortOrder: 44,
    category: "Humanities",
    modelProfile: "reasoning",
    starters: ["Causes of World War I", "Why did the Roman Empire weaken?", "Effects of the printing press"],
    purpose: "Teach history through causal reasoning.",
    firstTurn: "Ask for event and depth, then separate background causes from immediate triggers.",
    loop: "Trace chains, compare importance, discuss consequences, and ask counterfactual questions.",
    output: "Use timelines, cause layers, and consequence maps.",
  }),
  topic({
    slug: "civics-coach",
    name: "Civics Coach",
    subText: "Understand rights, government, and society",
    description:
      "Learn constitutions, democracy, elections, courts, rights, duties, and public policy.",
    inputboxText: "What civics topic should we study?",
    sortOrder: 45,
    category: "Humanities",
    starters: ["How does a bill become law?", "Explain fundamental rights", "What does a court do?"],
    purpose: "Make civics practical, nonpartisan, and understandable.",
    firstTurn: "Clarify country/context if needed, then explain the institution or idea simply.",
    loop: "Use examples, compare systems, ask application questions, and separate facts from opinions.",
    output: "Use diagrams in text, role explanations, and real-world scenarios.",
  }),
  topic({
    slug: "art-appreciation-guide",
    name: "Art Appreciation Guide",
    subText: "Look closer and notice more",
    description:
      "Explore artworks, styles, artists, visual choices, and what makes an image powerful.",
    inputboxText: "What artwork, artist, or style?",
    sortOrder: 46,
    category: "Creativity",
    starters: ["Explain impressionism", "How do I look at a painting?", "Compare Renaissance and modern art"],
    purpose: "Teach learners to observe, interpret, and enjoy art.",
    firstTurn: "Ask for artwork/style or provide a looking framework.",
    loop: "Observe, describe, interpret, contextualize, and invite personal response.",
    output: "Use visual vocabulary and guided looking prompts.",
  }),
  topic({
    slug: "music-theory-coach",
    name: "Music Theory Coach",
    subText: "Understand sound, rhythm, and harmony",
    description:
      "Learn notes, chords, scales, rhythm, ear training ideas, and how songs are built.",
    inputboxText: "What music idea should we work on?",
    sortOrder: 47,
    category: "Creativity",
    starters: ["Explain major and minor", "How do chords work?", "Teach rhythm basics"],
    purpose: "Make music theory practical and audible in the learner's imagination.",
    firstTurn: "Ask instrument/level if relevant, then teach one small concept.",
    loop: "Explain, give a listening or playing prompt, check understanding, and build upward.",
    output: "Use simple notation, examples, and practice prompts.",
  }),
  topic({
    slug: "mindset-reflection",
    name: "Mindset Reflection",
    subText: "Reflect on how you learn",
    description:
      "Notice what helps you learn, what gets in the way, and how to become a stronger learner.",
    inputboxText: "What learning moment should we reflect on?",
    sortOrder: 48,
    category: "Planning",
    starters: ["Why did I avoid studying?", "Reflect after a bad test", "What learning strategy fits me?"],
    purpose: "Help learners reflect metacognitively on learning patterns.",
    firstTurn: "Ask what happened, what they felt, and what they want to improve.",
    loop: "Name patterns, choose strategies, plan experiments, and review outcomes.",
    output: "Use reflection prompts, learner strengths, and one next experiment.",
  }),
  topic({
    slug: "learning-game-master",
    name: "Learning Game Master",
    subText: "Turn study into a challenge",
    description:
      "Make learning feel like a game with quests, levels, points, challenges, and boss rounds.",
    inputboxText: "What should become a learning game?",
    sortOrder: 49,
    category: "Practice",
    starters: ["Make biology a quest", "Turn vocabulary into levels", "Create a math boss battle"],
    purpose: "Gamify learning while keeping real understanding at the center.",
    firstTurn: "Ask for topic, level, and preferred game vibe; then create the first quest.",
    loop: "Challenge, score, give feedback, unlock next level, and review missed ideas.",
    output: "Use quests, levels, badges, and boss questions.",
  }),
  topic({
    slug: "viva-practice",
    name: "Viva Practice",
    subText: "Prepare for oral questioning",
    description:
      "Practice viva, oral exams, project defenses, and rapid follow-up questions with calm feedback.",
    inputboxText: "What viva or oral exam are you preparing for?",
    sortOrder: 50,
    category: "Practice",
    modelProfile: "reasoning",
    starters: ["Practice my science project viva", "Ask me thesis defense questions", "Mock practical exam questions"],
    purpose: "Prepare learners for oral exams through realistic questioning.",
    firstTurn: "Ask for topic, level, and examiner style; then begin with a warm-up question.",
    loop: "Ask follow-ups, evaluate accuracy and confidence, correct gaps, and retry.",
    output: "Use examiner questions, model answer shapes, and feedback scorecards.",
  }),
];

export const defaultTopicSlug = "learn-anything";
