export const siteConfig = {
  siteName: 'inspir',
  baseUrl: 'https://quiz.inspir.uk',
  locale: 'en_US',
  defaultTitle: 'inspir — AI Study Toolkit',
  titleTemplate: '%s | inspir',
  defaultDescription:
    'An AI-powered study toolkit: quizzes, step-by-step explanations, Cornell notes, citations, timers, and progress tools — in one place.',
  defaultKeywords: [
    'AI study tool',
    'AI study assistant',
    'AI tutor',
    'AI quiz generator',
    'quiz generator',
    'study tool',
    'active recall',
    'study from notes',
    'quiz from notes',
    'exam prep',
    'learning tool',
    'study timer',
    'citation generator',
  ],
  defaultImagePath: '/og-image.jpg',
};
