/* Generated by pnpm seo:lastmod:generate. Do not edit by hand. */

export const sitemapContentLastModified = {
  home: "2026-07-07",
  mission: "2026-07-07",
  about: "2026-07-07",
  schools: "2026-07-07",
  trust: "2026-07-07",
  media: "2026-07-07",
  topics: "2026-07-11",
  subjects: "2026-07-07",
  prompts: "2026-07-07",
  learningMap: "2026-07-07",
  compare: "2026-07-07",
  audience: "2026-07-07",
  learn: "2026-07-07",
  blog: "2026-07-07",
  learningPaths: "2026-07-07",
  comparisons: "2026-06-12",
  audiences: "2026-06-12",
  subjectPages: "2026-06-12",
  blogCategories: "2026-07-07"
} as const;
