const apexHostname = "inspirlearning.com";
const wwwHostname = "www.inspirlearning.com";

type RequestHeaders = Pick<Headers, "get">;

export function canonicalOriginRedirectUrl(inputUrl: URL, headers: RequestHeaders) {
  const url = new URL(inputUrl.toString());
  const explicitHostname = forwardedHostname(headers) ?? headerHostname(headers.get("host"));

  // OpenNext may construct an internal Next URL from APP_URL during local preview.
  // An explicit non-production Host is therefore authoritative and must never be
  // redirected merely because that internal URL uses the production hostname.
  if (explicitHostname && !isInspirHostname(explicitHostname)) return null;

  // `cf-ray` is generated by Cloudflare at the edge. Requiring it avoids
  // treating OpenNext's APP_URL-derived local Host/proto as public-edge proof.
  const cloudflareScheme = headers.get("cf-ray") ? cfVisitorScheme(headers.get("cf-visitor")) : null;
  const urlHostname = url.hostname.toLowerCase();
  const confirmedHostname =
    explicitHostname && isInspirHostname(explicitHostname)
      ? explicitHostname
      : cloudflareScheme && isInspirHostname(urlHostname)
        ? urlHostname
        : null;
  if (!confirmedHostname) return null;

  const needsHttps = cloudflareScheme === "http";
  const needsApex = confirmedHostname === wwwHostname;
  if (!needsHttps && !needsApex) return null;

  url.protocol = "https:";
  if (needsApex) {
    url.hostname = apexHostname;
    url.port = "";
  }
  return url;
}

function forwardedHostname(headers: RequestHeaders) {
  return headerHostname(headers.get("x-forwarded-host"));
}

function headerHostname(value: string | null) {
  const authority = firstHeaderValue(value);
  if (!authority) return null;
  try {
    return new URL(`https://${authority}`).hostname.toLowerCase();
  } catch {
    return null;
  }
}

function cfVisitorScheme(value: string | null) {
  if (!value) return null;
  try {
    const parsed: unknown = JSON.parse(value);
    if (!isRecord(parsed)) return null;
    return parsed.scheme === "http" || parsed.scheme === "https" ? parsed.scheme : null;
  } catch {
    return null;
  }
}

function firstHeaderValue(value: string | null) {
  return value?.split(",", 1)[0]?.trim() || null;
}

function isInspirHostname(hostname: string) {
  return hostname === apexHostname || hostname === wwwHostname;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}
