import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const sourceGroups = {
  home: ["app/(marketing)/page.tsx", "lib/content/landing.ts"],
  mission: ["app/(marketing)/mission/page.tsx", "lib/content/authority.ts"],
  about: ["app/(marketing)/about/page.tsx", "lib/content/authority.ts"],
  schools: ["app/(marketing)/schools/page.tsx", "lib/content/authority.ts"],
  trust: ["app/(marketing)/trust/page.tsx", "lib/content/authority.ts"],
  media: ["app/(marketing)/media/page.tsx", "lib/content/authority.ts"],
  topics: [
    "app/(marketing)/topics/page.tsx",
    "lib/content/topic-directory.ts",
    "lib/content/topic-public-seo.ts",
    "lib/content/topics.ts",
  ],
  subjects: ["app/(marketing)/subjects/page.tsx", "lib/content/subjects.ts"],
  prompts: ["app/(marketing)/prompts/page.tsx", "lib/content/prompt-library.ts"],
  learningMap: ["app/(marketing)/ai-learning-map/page.tsx", "lib/content/learning-map.ts"],
  compare: ["app/(marketing)/compare/page.tsx", "lib/content/comparisons.ts"],
  audience: ["app/(marketing)/for/page.tsx", "lib/content/audiences.ts"],
  learn: ["app/(marketing)/learn/page.tsx", "lib/content/landing.ts"],
  blog: [
    "app/(marketing)/blog/page.tsx",
    "lib/content/blog.ts",
    "lib/content/blog-directory.ts",
    "lib/content/blog-seo-policy.ts",
  ],
  learningPaths: ["lib/content/landing.ts"],
  comparisons: ["lib/content/comparisons.ts"],
  audiences: ["lib/content/audiences.ts"],
  subjectPages: ["lib/content/subjects.ts"],
  blogCategories: [
    "app/(marketing)/blog/category/[slug]/page.tsx",
    "lib/content/blog.ts",
    "lib/content/blog-directory.ts",
    "lib/content/blog-seo-policy.ts",
  ],
} as const satisfies Record<string, readonly string[]>;

const outputPath = path.resolve(process.cwd(), "lib/seo/content-lastmod.generated.ts");
const checkOnly = process.argv.includes("--check");

function gitLastCommitDate(files: readonly string[]) {
  const date = execFileSync("git", ["log", "-1", "--format=%cs", "--", ...files], {
    cwd: process.cwd(),
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();

  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error(`Could not resolve a git content date for ${files.join(", ")}`);
  }

  return date;
}

function buildOutput() {
  const entries = Object.entries(sourceGroups).map(([key, files]) => [key, gitLastCommitDate(files)] as const);
  const json = JSON.stringify(Object.fromEntries(entries), null, 2).replace(/"([^"]+)":/g, "$1:");

  return [
    "/* Generated by pnpm seo:lastmod:generate. Do not edit by hand. */",
    "",
    `export const sitemapContentLastModified = ${json} as const;`,
    "",
  ].join("\n");
}

const output = buildOutput();

if (checkOnly) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
  if (current !== output) {
    console.error("Sitemap lastmod data is stale. Run pnpm seo:lastmod:generate.");
    process.exitCode = 1;
  }
} else {
  writeFileSync(outputPath, output);
  console.log(JSON.stringify({ ok: true, outputPath, entries: Object.keys(sourceGroups).length }, null, 2));
}
