// Generated by `pnpm translations:generate-site-source-manifest`.
// Do not edit by hand.
import type { SupportedLanguage } from "@/lib/content/languages";

export const staticSiteTranslationNamespaceAvailability: Partial<Record<SupportedLanguage, readonly string[]>> = {
  "Hindi": [
    "marketing-shell",
    "route:home"
  ],
  "Spanish": [
    "marketing-shell",
    "route:home",
    "route:mission"
  ],
  "French": [
    "marketing-shell",
    "route:home"
  ],
  "German": [
    "marketing-shell",
    "route:home"
  ],
  "Italian": [
    "marketing-shell",
    "route:home"
  ],
  "Portuguese": [
    "marketing-shell",
    "route:home"
  ],
  "Dutch": [
    "marketing-shell",
    "route:home"
  ],
  "Russian": [
    "marketing-shell",
    "route:home"
  ],
  "Ukrainian": [
    "marketing-shell",
    "route:home"
  ],
  "Polish": [
    "marketing-shell",
    "route:home"
  ],
  "Romanian": [
    "marketing-shell",
    "route:home"
  ],
  "Czech": [
    "marketing-shell",
    "route:home"
  ],
  "Hungarian": [
    "marketing-shell",
    "route:home"
  ],
  "Greek": [
    "marketing-shell",
    "route:home"
  ],
  "Turkish": [
    "marketing-shell",
    "route:home"
  ],
  "Arabic": [
    "marketing-shell",
    "route:home"
  ],
  "Hebrew": [
    "marketing-shell",
    "route:home"
  ],
  "Persian": [
    "marketing-shell",
    "route:home"
  ],
  "Urdu": [
    "marketing-shell",
    "route:home"
  ],
  "Bengali": [
    "marketing-shell",
    "route:home"
  ],
  "Tamil": [
    "marketing-shell",
    "route:home"
  ],
  "Telugu": [
    "marketing-shell",
    "route:home"
  ],
  "Marathi": [
    "marketing-shell",
    "route:home"
  ],
  "Gujarati": [
    "marketing-shell",
    "route:home"
  ],
  "Kannada": [
    "marketing-shell",
    "route:home"
  ],
  "Malayalam": [
    "marketing-shell",
    "route:home"
  ],
  "Punjabi": [
    "marketing-shell",
    "route:home"
  ],
  "Odia": [
    "marketing-shell",
    "route:home"
  ],
  "Assamese": [
    "marketing-shell",
    "route:home"
  ],
  "Nepali": [
    "marketing-shell",
    "route:home"
  ],
  "Sinhala": [
    "marketing-shell",
    "route:home"
  ],
  "Chinese": [
    "marketing-shell",
    "route:home"
  ],
  "Japanese": [
    "marketing-shell",
    "route:home"
  ],
  "Korean": [
    "marketing-shell",
    "route:home"
  ],
  "Vietnamese": [
    "marketing-shell",
    "route:home"
  ],
  "Thai": [
    "marketing-shell",
    "route:home"
  ],
  "Indonesian": [
    "marketing-shell",
    "route:home"
  ],
  "Malay": [
    "marketing-shell",
    "route:home"
  ],
  "Filipino": [
    "marketing-shell",
    "route:home"
  ],
  "Swahili": [
    "marketing-shell",
    "route:home"
  ],
  "Afrikaans": [
    "marketing-shell",
    "route:home"
  ],
  "Amharic": [
    "marketing-shell",
    "route:home"
  ],
  "Yoruba": [
    "marketing-shell",
    "route:home"
  ],
  "Zulu": [
    "marketing-shell",
    "route:home"
  ],
  "Hausa": [
    "marketing-shell",
    "route:home"
  ],
  "Somali": [
    "marketing-shell",
    "route:home"
  ],
  "Norwegian": [
    "marketing-shell",
    "route:home"
  ],
  "Swedish": [
    "marketing-shell",
    "route:home"
  ],
  "Danish": [
    "marketing-shell",
    "route:home"
  ],
  "Finnish": [
    "marketing-shell",
    "route:home"
  ],
  "Icelandic": [
    "marketing-shell",
    "route:home"
  ],
  "Irish": [
    "marketing-shell",
    "route:home"
  ],
  "Welsh": [
    "marketing-shell",
    "route:home"
  ],
  "Catalan": [
    "marketing-shell",
    "route:home"
  ],
  "Basque": [
    "marketing-shell",
    "route:home"
  ],
  "Galician": [
    "marketing-shell",
    "route:home"
  ],
  "Serbian": [
    "marketing-shell",
    "route:home"
  ],
  "Croatian": [
    "marketing-shell",
    "route:home"
  ],
  "Bosnian": [
    "marketing-shell",
    "route:home"
  ],
  "Bulgarian": [
    "marketing-shell",
    "route:home"
  ],
  "Slovak": [
    "marketing-shell",
    "route:home"
  ],
  "Slovenian": [
    "marketing-shell",
    "route:home"
  ],
  "Lithuanian": [
    "marketing-shell",
    "route:home"
  ],
  "Latvian": [
    "marketing-shell",
    "route:home"
  ],
  "Estonian": [
    "marketing-shell",
    "route:home"
  ],
  "Albanian": [
    "marketing-shell",
    "route:home"
  ],
  "Georgian": [
    "marketing-shell",
    "route:home"
  ],
  "Armenian": [
    "marketing-shell",
    "route:home"
  ],
  "Azerbaijani": [
    "marketing-shell",
    "route:home"
  ]
} as const;
