import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import { Link } from 'react-router-dom';
import { useEffect } from 'react';

export default function FAQ() {
  // Add JSON-LD structured data for FAQ
  useEffect(() => {
    const script = document.createElement('script');
    script.type = 'application/ld+json';
    script.innerHTML = JSON.stringify({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "Is InspirQuiz really free?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, completely free. No hidden costs, no premium tiers, no credit card required. Create as many quizzes as you want."
          }
        },
        {
          "@type": "Question",
          "name": "Do I need to create an account?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "No, you can use InspirQuiz as a guest. Click 'Continue as Guest' and start creating quizzes immediately. If you want to save your quizzes for later, you can create a free account with just a username and password—no email required."
          }
        },
        {
          "@type": "Question",
          "name": "What file types can I upload?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "InspirQuiz supports .txt (plain text) and .docx (Microsoft Word) files. You can also paste text directly instead of uploading a file."
          }
        },
        {
          "@type": "Question",
          "name": "How many questions will my quiz have?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Every quiz generated by InspirQuiz has exactly 10 questions: 5 multiple choice questions and 5 open-ended questions."
          }
        },
        {
          "@type": "Question",
          "name": "How long does it take to generate a quiz?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Usually 10-20 seconds, depending on how much content you provide. The AI needs time to read your material and create thoughtful questions."
          }
        },
        {
          "@type": "Question",
          "name": "Can I edit the questions after they're generated?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Currently, you can't edit generated questions. If you're not happy with a quiz, you can regenerate it with the same content and you'll get different questions. We're considering adding editing features in the future."
          }
        },
        {
          "@type": "Question",
          "name": "Do you store my uploaded content?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "No. Your content is processed to generate the quiz, then it's discarded. We only save the generated quiz questions (if you're logged in), not your original source material."
          }
        },
        {
          "@type": "Question",
          "name": "What AI model do you use?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "InspirQuiz uses Claude Sonnet 4.5 from Anthropic, one of the most advanced language models available. It's specifically prompted to create educational, thought-provoking questions rather than surface-level recall questions."
          }
        },
        {
          "@type": "Question",
          "name": "Can teachers use this for their classes?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Absolutely. Many teachers use InspirQuiz to create quick assessments, homework assignments, and practice problems from their curriculum materials. It's a huge time-saver."
          }
        },
        {
          "@type": "Question",
          "name": "Can I share my quizzes with others?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes! After creating a quiz, click 'Share This Quiz' to get a unique link. Anyone with the link can take your quiz, whether they have an account or not."
          }
        },
        {
          "@type": "Question",
          "name": "Do people need an account to take my shared quiz?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "No! They can take it as a guest by simply entering their name. Or they can sign in if they already have an InspirQuiz account."
          }
        },
        {
          "@type": "Question",
          "name": "Can I see who took my shared quiz?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Absolutely! Click 'View Attempts' on any shared quiz to see all scores, names, timestamps, and performance stats. You'll see both guest and registered user attempts."
          }
        },
        {
          "@type": "Question",
          "name": "Are shared quiz links permanent?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, the share link works as long as you don't delete the quiz. You can share it multiple times with different people."
          }
        },
        {
          "@type": "Question",
          "name": "Can I stop sharing a quiz?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Currently, shared links remain active. If you want to stop sharing, you can delete the quiz, which will disable the link. We may add an unshare feature in the future."
          }
        },
        {
          "@type": "Question",
          "name": "Do guests' scores get saved?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes! All attempts (both guest and registered users) are recorded so you can track performance. Guests won't have a personal history, but you'll see their results as the quiz creator."
          }
        },
        {
          "@type": "Question",
          "name": "Why don't you collect email addresses?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Privacy. We don't need your email to provide the service, so we don't ask for it. Simple as that. This means we can't help with password recovery, but it also means we're not building a marketing database or tracking you."
          }
        },
        {
          "@type": "Question",
          "name": "How accurate are the quiz answers?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The AI is very good at understanding content and creating accurate questions, but like any AI system, it's not perfect. Always review the answers, especially for highly technical or specialized content. If you spot an error, regenerate the quiz or use it as a learning opportunity to catch incorrect information."
          }
        },
        {
          "@type": "Question",
          "name": "What is the Grade Calculator feature?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The Grade Calculator lets you track assignments with weighted scores, see real-time grade projections, run what-if scenarios to calculate what grade you need on future assignments, and track your GPA across multiple semesters. All data is stored locally in your browser."
          }
        },
        {
          "@type": "Question",
          "name": "Is my grade data saved?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, your grade calculator data is saved in your browser's local storage. This means your data persists between sessions, but it's only accessible on the device and browser you used. If you clear your browser data, your grades will be deleted."
          }
        }
      ]
    });
    document.head.appendChild(script);

    return () => {
      document.head.removeChild(script);
    };
  }, []);

  return (
    <>
      <Navigation />
      <main className="min-h-screen bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 py-12">
          <article>
            <h1 className="text-4xl md:text-5xl font-bold text-deep-blue mb-6">Frequently Asked Questions</h1>

            <div className="prose prose-lg max-w-none">
              <p className="text-xl text-gray-700 mb-8">
                Got questions about InspirQuiz? Here are the answers to the most common ones.
              </p>

              <div className="space-y-6">
                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Is InspirQuiz really free?</h2>
                  <p className="text-gray-700">
                    Yes, completely free. No hidden costs, no premium tiers, no credit card required.
                    Create as many quizzes as you want.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do I need to create an account?</h2>
                  <p className="text-gray-700 mb-3">
                    No, you can use InspirQuiz as a guest. Click "Continue as Guest" and start creating quizzes immediately.
                  </p>
                  <p className="text-gray-700">
                    If you want to save your quizzes for later, you can create a free account with just a username and
                    password—no email required.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What file types can I upload?</h2>
                  <p className="text-gray-700">
                    InspirQuiz supports .txt (plain text) and .docx (Microsoft Word) files. You can also paste text
                    directly instead of uploading a file.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How many questions will my quiz have?</h2>
                  <p className="text-gray-700">
                    Every quiz generated by InspirQuiz has exactly 10 questions: 5 multiple choice questions and
                    5 open-ended questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How long does it take to generate a quiz?</h2>
                  <p className="text-gray-700">
                    Usually 10-20 seconds, depending on how much content you provide. The AI needs time to read
                    your material and create thoughtful questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I edit the questions after they're generated?</h2>
                  <p className="text-gray-700 mb-3">
                    Currently, you can't edit generated questions. If you're not happy with a quiz, you can regenerate it
                    with the same content and you'll get different questions.
                  </p>
                  <p className="text-gray-700">
                    We're considering adding editing features in the future.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do you store my uploaded content?</h2>
                  <p className="text-gray-700">
                    No. Your content is processed to generate the quiz, then it's discarded. We only save the generated
                    quiz questions (if you're logged in), not your original source material.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What AI model do you use?</h2>
                  <p className="text-gray-700">
                    InspirQuiz uses Claude Sonnet 4.5 from Anthropic, one of the most advanced language models available.
                    It's specifically prompted to create educational, thought-provoking questions rather than surface-level
                    recall questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can teachers use this for their classes?</h2>
                  <p className="text-gray-700">
                    Absolutely. Many teachers use InspirQuiz to create quick assessments, homework assignments, and
                    practice problems from their curriculum materials. It's a huge time-saver.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I share my quizzes with others?</h2>
                  <p className="text-gray-700">
                    Yes! After creating a quiz, click "Share This Quiz" to get a unique link. Anyone with the link can take
                    your quiz, whether they have an account or not.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do people need an account to take my shared quiz?</h2>
                  <p className="text-gray-700">
                    No! They can take it as a guest by simply entering their name. Or they can sign in if they already have an
                    InspirQuiz account.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I see who took my shared quiz?</h2>
                  <p className="text-gray-700">
                    Absolutely! Click "View Attempts" on any shared quiz to see all scores, names, timestamps, and performance stats.
                    You'll see both guest and registered user attempts.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Are shared quiz links permanent?</h2>
                  <p className="text-gray-700">
                    Yes, the share link works as long as you don't delete the quiz. You can share it multiple times with different people.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I stop sharing a quiz?</h2>
                  <p className="text-gray-700">
                    Currently, shared links remain active. If you want to stop sharing, you can delete the quiz, which will disable
                    the link. (We may add an "unshare" feature in the future!)
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do guests' scores get saved?</h2>
                  <p className="text-gray-700">
                    Yes! All attempts (both guest and registered users) are recorded so you can track performance. Guests won't have
                    a personal history, but you'll see their results as the quiz creator.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Why don't you collect email addresses?</h2>
                  <p className="text-gray-700">
                    Privacy. We don't need your email to provide the service, so we don't ask for it. Simple as that.
                    This means we can't help with password recovery, but it also means we're not building a marketing
                    database or tracking you.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How accurate are the quiz answers?</h2>
                  <p className="text-gray-700 mb-3">
                    The AI is very good at understanding content and creating accurate questions, but like any AI system,
                    it's not perfect. Always review the answers, especially for highly technical or specialized content.
                  </p>
                  <p className="text-gray-700">
                    If you spot an error, regenerate the quiz or use it as a learning opportunity to catch incorrect information.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How much content should I provide?</h2>
                  <p className="text-gray-700 mb-3">
                    There's no strict limit, but generally 1-3 pages worth of text works well. That gives the AI enough
                    material to create diverse, thoughtful questions without being overwhelming.
                  </p>
                  <p className="text-gray-700">
                    Too little content (like a single paragraph) won't give you a great quiz. Too much (like an entire
                    textbook chapter) might result in very broad or surface-level questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I use this for languages other than English?</h2>
                  <p className="text-gray-700">
                    InspirQuiz is built primarily for English content, but the AI can handle other languages too.
                    Just be aware that question quality might vary for non-English content, especially for less common languages.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What if I forget my password?</h2>
                  <p className="text-gray-700 mb-3">
                    Unfortunately, we can't help you recover it. Since we don't collect email addresses, there's no way
                    to send a password reset link.
                  </p>
                  <p className="text-gray-700">
                    This is a trade-off for privacy. We recommend using a password manager to store your credentials,
                    or just continue using InspirQuiz as a guest.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Will you add more features in the future?</h2>
                  <p className="text-gray-700 mb-3">
                    Possibly. We're considering features like:
                  </p>
                  <ul className="list-disc pl-6 text-gray-700 space-y-1">
                    <li>Customizable quiz length (more or fewer than 10 questions)</li>
                    <li>Question editing and customization</li>
                    <li>Quiz sharing and collaboration</li>
                    <li>Progress tracking and spaced repetition</li>
                    <li>Support for more file types</li>
                  </ul>
                  <p className="text-gray-700 mt-3">
                    But we're committed to keeping InspirQuiz simple, fast, and privacy-focused. Any new features
                    will maintain those principles.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I use this commercially?</h2>
                  <p className="text-gray-700">
                    If you're a teacher, corporate trainer, or other professional using InspirQuiz to create educational
                    materials, that's totally fine. We're happy to support learning in any context.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What is the Grade Calculator feature?</h2>
                  <p className="text-gray-700 mb-3">
                    The Grade Calculator lets you track assignments with weighted scores, see real-time grade projections,
                    run what-if scenarios to calculate what grade you need on future assignments, and track your GPA across
                    multiple semesters.
                  </p>
                  <p className="text-gray-700">
                    All data is stored locally in your browser, so your information stays private and accessible only to you.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Is my grade data saved?</h2>
                  <p className="text-gray-700 mb-3">
                    Yes, your grade calculator data is saved in your browser's local storage. This means your data persists
                    between sessions, but it's only accessible on the device and browser you used.
                  </p>
                  <p className="text-gray-700">
                    If you clear your browser data, your grades will be deleted. We recommend exporting or backing up important
                    data if you're concerned about losing it.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">I found a bug or have a feature request. How do I report it?</h2>
                  <p className="text-gray-700 mb-3">
                    We'd love to hear from you! While we don't have a formal support system set up yet, you can
                    reach out through our social channels or check back here for updates.
                  </p>
                  <p className="text-gray-700">
                    We're a small operation focused on making the core product great, so we may not be able to respond
                    to everything, but we do read all feedback.
                  </p>
                </div>
              </div>

              <div className="bg-purple-gradient text-white rounded-lg p-8 text-center mt-12">
                <h2 className="text-2xl font-bold mb-4">Still Have Questions?</h2>
                <p className="mb-6">The best way to understand InspirQuiz is to try it yourself. It's free and takes less than a minute.</p>
                <Link to="/" className="inline-block bg-coral-red text-white px-8 py-3 rounded-lg font-bold hover:bg-opacity-90 transition-all">
                  Try InspirQuiz Now
                </Link>
              </div>
            </div>
          </article>
        </div>
      </main>
      <Footer />
    </>
  );
}
