import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import { Link } from 'react-router-dom';

export default function FAQ() {
  return (
    <>
      <Navigation />
      <main className="min-h-screen bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 py-12">
          <article>
            <h1 className="text-4xl md:text-5xl font-bold text-deep-blue mb-6">Frequently Asked Questions</h1>

            <div className="prose prose-lg max-w-none">
              <p className="text-xl text-gray-700 mb-8">
                Got questions about InspirQuiz? Here are the answers to the most common ones.
              </p>

              <div className="space-y-6">
                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Is InspirQuiz really free?</h2>
                  <p className="text-gray-700">
                    Yes, completely free. No hidden costs, no premium tiers, no credit card required.
                    Create as many quizzes as you want.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do I need to create an account?</h2>
                  <p className="text-gray-700 mb-3">
                    No, you can use InspirQuiz as a guest. Click "Continue as Guest" and start creating quizzes immediately.
                  </p>
                  <p className="text-gray-700">
                    If you want to save your quizzes for later, you can create a free account with just a username and
                    password—no email required.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What file types can I upload?</h2>
                  <p className="text-gray-700">
                    InspirQuiz supports .txt (plain text) and .docx (Microsoft Word) files. You can also paste text
                    directly instead of uploading a file.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How many questions will my quiz have?</h2>
                  <p className="text-gray-700">
                    Every quiz generated by InspirQuiz has exactly 10 questions: 5 multiple choice questions and
                    5 open-ended questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How long does it take to generate a quiz?</h2>
                  <p className="text-gray-700">
                    Usually 10-20 seconds, depending on how much content you provide. The AI needs time to read
                    your material and create thoughtful questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I edit the questions after they're generated?</h2>
                  <p className="text-gray-700 mb-3">
                    Currently, you can't edit generated questions. If you're not happy with a quiz, you can regenerate it
                    with the same content and you'll get different questions.
                  </p>
                  <p className="text-gray-700">
                    We're considering adding editing features in the future.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do you store my uploaded content?</h2>
                  <p className="text-gray-700">
                    No. Your content is processed to generate the quiz, then it's discarded. We only save the generated
                    quiz questions (if you're logged in), not your original source material.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What AI model do you use?</h2>
                  <p className="text-gray-700">
                    InspirQuiz uses Claude (by Anthropic) to generate quizzes and explanations. We may upgrade or change
                    model versions over time, but the goal stays the same: questions that test understanding, not just
                    surface-level recall.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can teachers use this for their classes?</h2>
                  <p className="text-gray-700">
                    Absolutely. Many teachers use InspirQuiz to create quick assessments, homework assignments, and
                    practice problems from their curriculum materials. It's a huge time-saver.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I share my quizzes with others?</h2>
                  <p className="text-gray-700">
                    Yes! After creating a quiz, click "Share This Quiz" to get a unique link. Anyone with the link can take
                    your quiz, whether they have an account or not.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do people need an account to take my shared quiz?</h2>
                  <p className="text-gray-700">
                    No! They can take it as a guest by simply entering their name. Or they can sign in if they already have an
                    InspirQuiz account.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I see who took my shared quiz?</h2>
                  <p className="text-gray-700">
                    Absolutely! Click "View Attempts" on any shared quiz to see all scores, names, timestamps, and performance stats.
                    You'll see both guest and registered user attempts.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Are shared quiz links permanent?</h2>
                  <p className="text-gray-700">
                    Yes, the share link works as long as you don't delete the quiz. You can share it multiple times with different people.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I stop sharing a quiz?</h2>
                  <p className="text-gray-700">
                    Currently, shared links remain active. If you want to stop sharing, you can delete the quiz, which will disable
                    the link. (We may add an "unshare" feature in the future!)
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do guests' scores get saved?</h2>
                  <p className="text-gray-700">
                    Yes! All attempts (both guest and registered users) are recorded so you can track performance. Guests won't have
                    a personal history, but you'll see their results as the quiz creator.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Why don't you collect email addresses?</h2>
                  <p className="text-gray-700">
                    We keep signup lightweight and collect the minimum needed to run the product. Not collecting email
                    reduces risk and avoids turning the app into a marketing list. The trade-off is that password recovery
                    is limited—use a password manager if you create an account.
                  </p>
                  <p className="text-gray-700 mt-3">
                    For details on what we store and why, see our <Link to="/privacy" className="text-purple-dark font-semibold hover:underline">Privacy Policy</Link>.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How accurate are the quiz answers?</h2>
                  <p className="text-gray-700 mb-3">
                    The AI is very good at understanding content and creating accurate questions, but like any AI system,
                    it's not perfect. Always review the answers, especially for highly technical or specialized content.
                  </p>
                  <p className="text-gray-700">
                    If you spot an error, regenerate the quiz or use it as a learning opportunity to catch incorrect information.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">How much content should I provide?</h2>
                  <p className="text-gray-700 mb-3">
                    There's no strict limit, but generally 1-3 pages worth of text works well. That gives the AI enough
                    material to create diverse, thoughtful questions without being overwhelming.
                  </p>
                  <p className="text-gray-700">
                    Too little content (like a single paragraph) won't give you a great quiz. Too much (like an entire
                    textbook chapter) might result in very broad or surface-level questions.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I use this for languages other than English?</h2>
                  <p className="text-gray-700">
                    InspirQuiz is built primarily for English content, but the AI can handle other languages too.
                    Just be aware that question quality might vary for non-English content, especially for less common languages.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What if I forget my password?</h2>
                  <p className="text-gray-700 mb-3">
                    Unfortunately, we can't help you recover it. Since we don't collect email addresses, there's no way
                    to send a password reset link.
                  </p>
                  <p className="text-gray-700">
                    This is a trade-off for privacy. We recommend using a password manager to store your credentials,
                    or just continue using InspirQuiz as a guest.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Will you add more features in the future?</h2>
                  <p className="text-gray-700 mb-3">
                    Possibly. We're considering features like:
                  </p>
                  <ul className="list-disc pl-6 text-gray-700 space-y-1">
                    <li>Customizable quiz length (more or fewer than 10 questions)</li>
                    <li>Question editing and customization</li>
                    <li>Quiz sharing and collaboration</li>
                    <li>Progress tracking and spaced repetition</li>
                    <li>Support for more file types</li>
                  </ul>
                  <p className="text-gray-700 mt-3">
                    But we're committed to keeping InspirQuiz simple, fast, and privacy-focused. Any new features
                    will maintain those principles.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Can I use this commercially?</h2>
                  <p className="text-gray-700">
                    If you're a teacher, corporate trainer, or other professional using InspirQuiz to create educational
                    materials, that's totally fine. We're happy to support learning in any context.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What is the Grade Calculator feature?</h2>
                  <p className="text-gray-700 mb-3">
                    The Grade Calculator lets you track assignments with weighted scores, see real-time grade projections,
                    run what-if scenarios to calculate what grade you need on future assignments, and track your GPA across
                    multiple semesters.
                  </p>
                  <p className="text-gray-700">
                    All data is stored locally in your browser, so your information stays private and accessible only to you.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Is my grade data saved?</h2>
                  <p className="text-gray-700 mb-3">
                    Yes, your grade calculator data is saved in your browser's local storage. This means your data persists
                    between sessions, but it's only accessible on the device and browser you used.
                  </p>
                  <p className="text-gray-700">
                    If you clear your browser data, your grades will be deleted. We recommend exporting or backing up important
                    data if you're concerned about losing it.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">What are the other study tools?</h2>
                  <p className="text-gray-700 mb-3">
                    InspirQuiz includes a few focused tools designed to support active recall and better study workflows:
                  </p>
                  <ul className="list-disc pl-6 text-gray-700 space-y-1">
                    <li><Link to="/study-timer" className="text-purple-dark font-semibold hover:underline">Study Timer</Link> for Pomodoro-style focus sessions</li>
                    <li><Link to="/cornell-notes" className="text-purple-dark font-semibold hover:underline">Cornell Notes</Link> to turn content into cue-based notes</li>
                    <li><Link to="/citations" className="text-purple-dark font-semibold hover:underline">Citation Generator</Link> to keep sources organized</li>
                    <li><Link to="/streaks" className="text-purple-dark font-semibold hover:underline">Study Streaks</Link> to build consistent habits</li>
                    <li><Link to="/doubt" className="text-purple-dark font-semibold hover:underline">Doubt Solver</Link> for step-by-step explanations</li>
                  </ul>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">Do you have an AI chat assistant?</h2>
                  <p className="text-gray-700">
                    Yes—InspirQuiz includes an AI Chat experience for studying and Q&A. Because it’s tied to your account,
                    you may need to sign in to use it.
                  </p>
                </div>

                <div className="bg-white p-6 rounded-lg shadow-sm">
                  <h2 className="text-2xl font-bold text-deep-blue mb-3">I found a bug or have a feature request. How do I report it?</h2>
                  <p className="text-gray-700 mb-3">
                    The simplest option is to post in the <Link to="/forum" className="text-purple-dark font-semibold hover:underline">Student Forum</Link>.
                    Include what you expected to happen, what actually happened, and (if possible) a screenshot.
                  </p>
                  <p className="text-gray-700">
                    We're a small operation focused on making the core product great, so we may not be able to respond
                    to everything, but we do read all feedback.
                  </p>
                </div>
              </div>

              <div className="bg-purple-gradient text-white rounded-lg p-8 text-center mt-12">
                <h2 className="text-2xl font-bold mb-4">Still Have Questions?</h2>
                <p className="mb-6">The best way to understand InspirQuiz is to try it yourself. It's free and takes less than a minute.</p>
                <Link to="/" className="inline-block bg-coral-red text-white px-8 py-3 rounded-lg font-bold hover:bg-opacity-90 transition-all">
                  Try InspirQuiz Now
                </Link>
              </div>
            </div>
          </article>
        </div>
      </main>
      <Footer />
    </>
  );
}
