export const DATABASE_CONNECTION_ENV_NAMES = [
  "SUPABASE_DB_URL",
  "SUPABASE_DATABASE_URL",
  "POSTGRES_URL",
  "POSTGRES_PRISMA_URL",
  "DATABASE_URL",
  "DATABASE_URL_UNPOOLED",
] as const;

export const RETIRED_SUPABASE_ENV_KEYS = [
  ...DATABASE_CONNECTION_ENV_NAMES,
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "NEXT_PUBLIC_SUPABASE_URL",
  "SUPABASE_ANON_KEY",
  "SUPABASE_JWT_SECRET",
  "SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SECRET_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "SUPABASE_URL",
] as const;

export const RETIRED_VERCEL_RUNTIME_ENV_KEYS = [
  "VERCEL",
  "VERCEL_ENV",
  "VERCEL_GIT_COMMIT_AUTHOR_LOGIN",
  "VERCEL_GIT_COMMIT_AUTHOR_NAME",
  "VERCEL_GIT_COMMIT_MESSAGE",
  "VERCEL_GIT_COMMIT_REF",
  "VERCEL_GIT_COMMIT_SHA",
  "VERCEL_GIT_PREVIOUS_SHA",
  "VERCEL_GIT_PROVIDER",
  "VERCEL_GIT_PULL_REQUEST_ID",
  "VERCEL_GIT_REPO_ID",
  "VERCEL_GIT_REPO_OWNER",
  "VERCEL_GIT_REPO_SLUG",
  "VERCEL_OIDC_TOKEN",
  "VERCEL_TARGET_ENV",
  "VERCEL_URL",
] as const;

export const RETIRED_BUILD_TOOLING_ENV_KEYS = [
  "NX_DAEMON",
  "TURBO_CACHE",
  "TURBO_DOWNLOAD_LOCAL_ENABLED",
  "TURBO_REMOTE_ONLY",
  "TURBO_RUN_SUMMARY",
] as const;

export const RETIRED_TRANSLATION_BUILD_ENV_KEYS = [
  "GEMINI_API_KEY",
  "GEMINI_TRANSLATION_MODEL",
  "OPENAI_TRANSLATION_CONCURRENCY",
  "OPENAI_TRANSLATION_FIELDS_PER_REQUEST",
  "OPENAI_TRANSLATION_MAX_RETRIES",
  "OPENAI_TRANSLATION_MODEL",
  "OPENAI_TRANSLATION_RETRY_DELAY_MS",
  "OPENAI_TRANSLATION_TIMEOUT_MS",
  "TRANSLATION_PROVIDER",
] as const;

export const RETIRED_PROVIDER_ENV_KEYS = [
  ...new Set([
    ...RETIRED_SUPABASE_ENV_KEYS,
    ...RETIRED_VERCEL_RUNTIME_ENV_KEYS,
    ...RETIRED_BUILD_TOOLING_ENV_KEYS,
    ...RETIRED_TRANSLATION_BUILD_ENV_KEYS,
  ]),
] as const;

export const FORBIDDEN_ENV_AFTER_ROTATION = [
  "CLOUDFLARE_API_TOKEN",
  "CF_API_TOKEN",
  "CLOUDFLARE_API_TOKEN_FILE",
  "CF_API_TOKEN_FILE",
  "R2_ACCESS_KEY_ID",
  "R2_SECRET_ACCESS_KEY",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "VERCEL_TOKEN",
  "SUPABASE_ACCESS_TOKEN",
  "SUPABASE_DB_PASSWORD",
  ...RETIRED_PROVIDER_ENV_KEYS,
] as const;

export function isRetiredProviderEnvKey(key: string): boolean {
  return (RETIRED_PROVIDER_ENV_KEYS as readonly string[]).includes(key);
}

export function isRetiredSupabaseEnvKey(key: string): boolean {
  return (RETIRED_SUPABASE_ENV_KEYS as readonly string[]).includes(key);
}

export function isRetiredVercelRuntimeEnvKey(key: string): boolean {
  return (RETIRED_VERCEL_RUNTIME_ENV_KEYS as readonly string[]).includes(key);
}

export function isRetiredBuildToolingEnvKey(key: string): boolean {
  return (RETIRED_BUILD_TOOLING_ENV_KEYS as readonly string[]).includes(key);
}

export function isRetiredTranslationBuildEnvKey(key: string): boolean {
  return (RETIRED_TRANSLATION_BUILD_ENV_KEYS as readonly string[]).includes(key);
}
