import fs from "node:fs";
import path from "node:path";
import {
  getAllSiteTranslationNamespaces,
  getSiteSourceHash,
  getSiteSourceStrings,
  siteTranslationNamespace,
} from "@/lib/i18n/site-source";

const namespaces = [siteTranslationNamespace, ...getAllSiteTranslationNamespaces({ mode: "extract" })];
const manifest: Record<string, { sourceHash: string; sourceStrings: Record<string, string> }> = {};

for (const namespace of namespaces) {
  const sourceStrings = getSiteSourceStrings(namespace, { mode: "extract" });
  manifest[namespace] = {
    sourceHash: getSiteSourceHash(sourceStrings),
    sourceStrings,
  };
}

const outputPath = path.resolve(process.cwd(), "lib/i18n/site-source-manifest.ts");
const output = [
  "// Generated by `pnpm translations:generate-site-source-manifest`.",
  "// Do not edit by hand.",
  `export const siteSourceManifest = ${JSON.stringify(manifest, null, 2)} as const;`,
  "",
].join("\n");

fs.writeFileSync(outputPath, output);
console.log(
  JSON.stringify(
    {
      outputPath,
      namespaces: namespaces.length,
      strings: Object.values(manifest).reduce((sum, entry) => sum + Object.keys(entry.sourceStrings).length, 0),
    },
    null,
    2,
  ),
);
