import fs from "node:fs";
import path from "node:path";
import {
  defaultLanguage,
  supportedLanguages,
  type SupportedLanguage,
} from "@/lib/content/languages";
import { getCuratedTranslationBundle } from "@/lib/i18n/curated-translations";
import { isRenderLocalizedSiteTranslationNamespace } from "@/lib/i18n/render-localized-namespaces";
import {
  getAllSiteTranslationNamespaces,
  getSiteSourceHash,
  getSiteSourceStrings,
  siteTranslationNamespace,
} from "@/lib/i18n/site-source";
import { isTranslationBundleCompleteAndFluent } from "@/lib/i18n/translation-quality";
import type { TranslationSource } from "@/lib/i18n/translation-types";

const namespaces = [siteTranslationNamespace, ...getAllSiteTranslationNamespaces({ mode: "extract" })];
const manifest: Record<string, { sourceHash: string; sourceStrings: Record<string, string> }> = {};
const availability: Partial<Record<SupportedLanguage, string[]>> = {};

for (const namespace of namespaces) {
  const sourceStrings = getSiteSourceStrings(namespace, { mode: "extract" });
  manifest[namespace] = {
    sourceHash: getSiteSourceHash(sourceStrings),
    sourceStrings,
  };
}

for (const language of supportedLanguages) {
  if (language === defaultLanguage) continue;

  const availableNamespaces = namespaces
    .filter((namespace) => namespace !== siteTranslationNamespace)
    .filter((namespace) => isRenderLocalizedSiteTranslationNamespace(namespace))
    .filter((namespace) => {
      const source = sourceFromManifestEntry(namespace, manifest[namespace]);
      const bundle = getCuratedTranslationBundle(source, language);
      return isTranslationBundleCompleteAndFluent(source, bundle, language);
    });

  if (availableNamespaces.length) availability[language] = availableNamespaces;
}

const outputPath = path.resolve(process.cwd(), "lib/i18n/site-source-manifest.ts");
const output = [
  "// Generated by `pnpm translations:generate-site-source-manifest`.",
  "// Do not edit by hand.",
  `export const siteSourceManifest = ${JSON.stringify(manifest, null, 2)} as const;`,
  "",
].join("\n");

fs.writeFileSync(outputPath, output);

const availabilityOutputPath = path.resolve(process.cwd(), "lib/i18n/site-availability-manifest.ts");
const availabilityOutput = [
  "// Generated by `pnpm translations:generate-site-source-manifest`.",
  "// Do not edit by hand.",
  'import type { SupportedLanguage } from "@/lib/content/languages";',
  "",
  `export const staticSiteTranslationNamespaceAvailability: Partial<Record<SupportedLanguage, readonly string[]>> = ${JSON.stringify(availability, null, 2)} as const;`,
  "",
].join("\n");

fs.writeFileSync(availabilityOutputPath, availabilityOutput);
console.log(
  JSON.stringify(
    {
      outputPath,
      availabilityOutputPath,
      namespaces: namespaces.length,
      strings: Object.values(manifest).reduce((sum, entry) => sum + Object.keys(entry.sourceStrings).length, 0),
      availabilityLanguages: Object.keys(availability).length,
      availabilityNamespaces: Object.values(availability).reduce((sum, entry) => sum + entry.length, 0),
    },
    null,
    2,
  ),
);

function sourceFromManifestEntry(
  namespace: string,
  entry: { sourceHash: string; sourceStrings: Record<string, string> },
): TranslationSource {
  return {
    namespace,
    sourceHash: entry.sourceHash,
    sourceStrings: entry.sourceStrings,
    systemInstruction: "",
  };
}
